name: Unit Tests
description: Action to run unit tests

runs:
  using: composite
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: pnpm exec playwright install --with-deps chromium

    - name: Tests
      shell: bash
      run: pnpm test
