name: Chromatic

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup and Install dependencies
        uses: ./.github/actions/setup

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Skip Chromatic on renovate PRs
          skip: ${{ github.actor == 'renovate[bot]' }}
          # Exit with code 0 even if there are changes
          exitZeroOnChanges: true
          # Add branch name to build title
          branchName: ${{ github.ref_name }}
